export interface Invitado {
  id: number
  nombre: string
  invitados: number
  adicional: number
}

export const listaInvitados: Invitado[] = [
  { id: 1, nombre: "Familia Casasola Juarez", invitados: 3, adicional: 0 },
  { id: 2, nombre: "Familia Juarez Solis", invitados: 5, adicional: 1 },
  { id: 3, nombre: "Familia Garcia Juarez", invitados: 3, adicional: 1 },
  { id: 4, nombre: "Jose & July", invitados: 2, adicional: 0 },
  { id: 5, nombre: "Renato Juarez", invitados: 2, adicional: 0 },
  { id: 6, nombre: "Familia Juarez Donis", invitados: 2, adicional: 0 },
  { id: 7, nombre: "Rocio Juarez", invitados: 1, adicional: 0 },
  { id: 8, nombre: "Paty y Roberto", invitados: 4, adicional: 0 },
  { id: 9, nombre: "Tia Irma", invitados: 1, adicional: 0 },
  { id: 10, nombre: "Rosaura Wilkinson", invitados: 2, adicional: 0 },
  { id: 11, nombre: "Geovany & Dulce", invitados: 2, adicional: 0 },
  { id: 12, nombre: "Tia Mary", invitados: 1, adicional: 0 },
  { id: 13, nombre: "Alexhey & Elizabeth", invitados: 2, adicional: 0 },
  { id: 14, nombre: "Jose Manuel Donis", invitados: 2, adicional: 0 },
  { id: 15, nombre: "Erick Peruch & Fam", invitados: 4, adicional: 0 },
  { id: 16, nombre: "Elfego & Rubi", invitados: 2, adicional: 0 },
  { id: 17, nombre: "Gonzalo", invitados: 1, adicional: 0 },
  { id: 18, nombre: "Karla", invitados: 1, adicional: 0 },
  { id: 19, nombre: "Barbara", invitados: 1, adicional: 0 },
  { id: 20, nombre: "Padre Cristian", invitados: 2, adicional: 0 },
  { id: 21, nombre: "Valdemar y Señora", invitados: 2, adicional: 0 },
  { id: 22, nombre: "Selvin y Señora", invitados: 2, adicional: 0 },
  { id: 23, nombre: "Jhonatan y Señora", invitados: 2, adicional: 0 },
  { id: 24, nombre: "Edna Alvarez", invitados: 1, adicional: 0 },
  { id: 25, nombre: "Juan Alvarez y Familia", invitados: 3, adicional: 0 },
  { id: 26, nombre: "Oslec Alvarez y Señora", invitados: 2, adicional: 0 },
  { id: 27, nombre: "Hugo Hernandez", invitados: 1, adicional: 0 },
  { id: 28, nombre: "Walter Hernandez", invitados: 1, adicional: 0 },
  { id: 29, nombre: "Katty Alvarez", invitados: 1, adicional: 0 },
  { id: 30, nombre: "Gloria Hernandez", invitados: 1, adicional: 0 },
  { id: 31, nombre: "Buenaventura Donis y Fam", invitados: 2, adicional: 0 },
  { id: 32, nombre: "Victor Alvarez y Fam", invitados: 2, adicional: 0 },
  { id: 33, nombre: "Luis Gomez y Esposa", invitados: 2, adicional: 0 },
  { id: 34, nombre: "Ever Santis y Esposa", invitados: 2, adicional: 0 },
  { id: 35, nombre: "Randolfo Villegas y Esposa", invitados: 2, adicional: 0 },
  { id: 36, nombre: "Mirella Villegas y Familia", invitados: 3, adicional: 0 },
  { id: 37, nombre: "Cesar Solares y Fam", invitados: 3, adicional: 0 },
  { id: 38, nombre: "Rodolfo Solorzano y Fam", invitados: 4, adicional: 0 },
  { id: 39, nombre: "Marlon Belteton", invitados: 1, adicional: 0 },
  { id: 40, nombre: "Marlon Puente", invitados: 1, adicional: 0 },
  { id: 41, nombre: "Eddy Estrada", invitados: 1, adicional: 0 },
  { id: 42, nombre: "Edgar Reyes", invitados: 1, adicional: 0 },
  { id: 43, nombre: "Maridalma Donis", invitados: 2, adicional: 0 },
  { id: 44, nombre: "Delida Donis", invitados: 1, adicional: 0 },
  { id: 45, nombre: "Mayra Alvarez", invitados: 2, adicional: 0 },
  { id: 46, nombre: "Rosi Alvarez", invitados: 2, adicional: 0 },
  { id: 47, nombre: "Luis Valdez", invitados: 2, adicional: 0 },
  { id: 48, nombre: "Marta de Valdez", invitados: 1, adicional: 0 },
  { id: 49, nombre: "William Lopez", invitados: 2, adicional: 0 },
  { id: 50, nombre: "ZOILA RIVERA DE OCAÑA", invitados: 2, adicional: 0 },
  { id: 51, nombre: "HERLINDA VILLEGAS", invitados: 2, adicional: 0 },
  { id: 52, nombre: "MIRIAM GUZMAN", invitados: 1, adicional: 0 },
  { id: 53, nombre: "CRUZ VILLEGAS", invitados: 1, adicional: 0 },
  { id: 54, nombre: "ELENA MEJIA", invitados: 1, adicional: 0 },
  { id: 55, nombre: "INGRID SANTOS", invitados: 1, adicional: 0 },
  { id: 56, nombre: "NIDIA SANTOS", invitados: 1, adicional: 0 },
  { id: 57, nombre: "FRANCISCO SANTOS", invitados: 1, adicional: 0 },
  { id: 58, nombre: "ANA MARÍA VILLEGAS", invitados: 1, adicional: 0 },
  { id: 59, nombre: "GLORIA VILLEGAS", invitados: 1, adicional: 0 },
  { id: 60, nombre: "DARIO FUENTES", invitados: 3, adicional: 0 },
  { id: 61, nombre: "ROSALINA VILLEGAS", invitados: 4, adicional: 0 },
  { id: 62, nombre: "ROLANDO VASQUEZ", invitados: 1, adicional: 0 },
  { id: 63, nombre: "DULCE MONTERROSA", invitados: 2, adicional: 0 },
  { id: 64, nombre: "CARLILY SIERRA", invitados: 2, adicional: 0 },
  { id: 65, nombre: "PAOLA DE FRANCO", invitados: 2, adicional: 0 },
  { id: 66, nombre: "JAMILET DE BARRIENTOS", invitados: 2, adicional: 0 },
  { id: 67, nombre: "KARINA GODOY", invitados: 2, adicional: 0 },
  { id: 68, nombre: "BLANCA VILLEGAS", invitados: 1, adicional: 0 },
  { id: 69, nombre: "HILDA GONZALEZ", invitados: 1, adicional: 0 },
  { id: 70, nombre: "MINDY LUNA", invitados: 1, adicional: 0 },
  { id: 71, nombre: "MARGA REYES", invitados: 2, adicional: 0 },
  { id: 72, nombre: "CLARA OCAÑA", invitados: 2, adicional: 0 },
  { id: 73, nombre: "GUISELA OCAÑA", invitados: 2, adicional: 0 },
  { id: 74, nombre: "ROSARIO VELA", invitados: 5, adicional: 0 },
  { id: 75, nombre: "SARA MEDRANO", invitados: 4, adicional: 0 },
  { id: 76, nombre: "ELSA GRIJALVA", invitados: 3, adicional: 0 },
  { id: 77, nombre: "JENNIFER FONSEA", invitados: 2, adicional: 0 },
  { id: 78, nombre: "KARLA TORO", invitados: 1, adicional: 0 },
  { id: 79, nombre: "RONY GONZALEZ", invitados: 2, adicional: 0 },
  { id: 80, nombre: "ROSARIO REYES", invitados: 1, adicional: 0 },
  { id: 81, nombre: "KARINA GONZALEZ", invitados: 2, adicional: 0 },
  { id: 82, nombre: "ELVIA IBARRA", invitados: 2, adicional: 0 },
  { id: 83, nombre: "JENNY PEREZ", invitados: 2, adicional: 0 },
  { id: 84, nombre: "NOE PEREZ", invitados: 1, adicional: 0 },
  { id: 85, nombre: "JOSELINE MEJIA", invitados: 2, adicional: 0 },
  { id: 86, nombre: "ALY DE BODE", invitados: 2, adicional: 0 },
  { id: 87, nombre: "EDNA GONZALEZ", invitados: 2, adicional: 0 },
  { id: 88, nombre: "ZUILMA FLORES", invitados: 2, adicional: 0 },
  { id: 89, nombre: "EMILIO DURANTE", invitados: 2, adicional: 0 },
  { id: 90, nombre: "SILVIA ARGUETA", invitados: 1, adicional: 0 },
  { id: 91, nombre: "MILDRED MAZARIEGOS", invitados: 2, adicional: 0 },
  { id: 92, nombre: "KARLA DAVILA", invitados: 2, adicional: 0 }
]
